### ISSUE TITLE
Descent dice

### ISSUE THREAD

**Issue by aeciobf** [BernhardPosselt/foundryvtt-special-dice-roller#17]
Hello!
I would like to make a suggestion: add the FFG Descent dice.

Great work!
Thanks!

**Comment by BernhardPosselt** [comment]
If you can come up with some open licensed images, why not.

**Comment by aeciobf** [comment]
Hello!

I'm not good in image editors, but find this material for Descent 1e.
https://www.boardgamegeek.com/filepage/56448/descent-dice

I am contacting the author to request permission to change images for Descent 2e.

**Comment by j0ran** [comment]
I am the author of those images. You are free to use them. I declare them to have a CC0 license. I did use the images to make a dice roller app for Android. That app was taken down by Fantasy Flight Games. Just to let you know.

**Comment by aeciobf** [comment]
Thank you, @j0ran!
Much appreciated for your help!

I made changes to the original file and here is the version for Descent 2e.

Any problem, let me know.

[DescentDice.zip](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/files/5024259/DescentDice.zip)

**Comment by BernhardPosselt** [comment]
Very cool, will work on it maybe this or next week end.

**Comment by BernhardPosselt** [comment]
BTW, you can contribute it as well earlier, there are some docs in the docs folder on how to implement a roller

**Comment by Skouic** [comment]
Hello,
Thx for your module Bernhard.
I’m also interested by descent v2 dices. Is still on going ? (I will try to add it by my own. But I’m totally newb)

**Comment by BernhardPosselt** [comment]
Yep, PF2 is keeping me busy right now and had to do a large Angular refactoring so not a lot of time left ;)

As for the dice: we probably should roll all of them in one go right? Armor + Attack dice. And IIRC armor symbols reduce damage symbols? Been 2 years since I had the chance to play Descent 2e.

**Comment by BernhardPosselt** [comment]
@Skouic if you could create a separate image file for each die face for 2e then I can take care of the implementation

**Comment by Skouic** [comment]
Yes you could roll both attack and defence dices. The armors reduce damage symbols but external skills or items could influence the final result. 
In the zip file provided by aeciobf the images are already separated for each faces. Do you need more than that ?

**Comment by BernhardPosselt** [comment]
@Skouic yep, the dice are different for 2e and it's a giant svg file not a zip afaik

**Comment by Skouic** [comment]
[DescentV2Dices.zip](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/files/5610991/DescentV2Dices.zip)
Ok the files seems to be the good one from the V2 but in case of you will find attached others images of the dices I have (symbols are bigger and it's better from my point of view)

**Comment by BernhardPosselt** [comment]
Thanks, looking good, will take a look :)

**Comment by BernhardPosselt** [comment]
First rough and untested implementation here https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/pull/24

Just wondering what the alphabet should be, I went with 

r: red
b: blue
y: yellow
g: green
l: brown (low defense)
m: grey (medium defense)
h: black (high defense)

**Comment by Skouic** [comment]
can I help you for the test ?

**Comment by BernhardPosselt** [comment]
No but you can tell me if the above characters work well.

**Comment by Skouic** [comment]
Yes it's fine for me
