### ISSUE TITLE
[Question] Will this be supported after the newest 0.7x update?

### ISSUE THREAD

**Issue by ThroughlyDruxy** [BernhardPosselt/foundryvtt-special-dice-roller#18]
So this is a question. I want to add the dice system from The One Ring but don't know if it's worth the effort if it won't be supported in the next update.

**Comment by BernhardPosselt** [comment]
What makes you think it won't? There's nothing special that .7.x does to break it.

**Comment by BernhardPosselt** [comment]
The One Ring looks like regular d6 right? This roller is mainly made for the custom FFG dice that can't be replaced using regular dice.

**Comment by ThroughlyDruxy** [comment]
It uses a D12 that has 1-10, then an "eye of sauron" (0) and a gandalf rune
which is an auto success. And the D6s have 1-3 that are not counted
depending on character status and a special symbol on the 6. Is there
another way to just use regular dice for foundry with the 11 and 12 on the
D12 swapped with images/symbols?
- Adam Cottrell

**Comment by BernhardPosselt** [comment]
So  the 0 on the D12 is an automatic failure and the 11 a success? That will work using the new dice roll API (see https://gitlab.com/foundrynet/foundryvtt/-/issues/3266)

The new API will also have support for 2D20 systems which should work similar to the D6s in that case. I think you can roll a number of dice and count all rolls greater than a number:

    /r 3d6cs>=4

for instance will roll 3d6 and display the number of results higher equal than 4

**Comment by BernhardPosselt** [comment]
the one ring was implemented by https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/pull/19 so I'm closing this issue
