### ISSUE TITLE
Request: interaction with DiceSoNice for 3d math rocks

### ISSUE THREAD

**Issue by CharlesRampant** [BernhardPosselt/foundryvtt-special-dice-roller#22]
It's not the end of the world to not have 3d dice for the L5R system, but it'd be really nice to have them.

**Comment by BernhardPosselt** [comment]
I'm not sure how that interacts with copyright if you get too close to the original dice. We would be very close to https://play.google.com/store/apps/details?id=com.FantasyFlightGames.DiceEngine&hl=de_AT&gl=US

I'd like to stay close to the Discord Dice bot which has been popularized on the FFG forums and has proven to not get the ban hammer from FFG. You can however work on a module that glues both together and I'll create the callback APIs to let you know the rolls being made if you want to.

PS: you'll likely need a completely different set of dice images for it to look even remotely passable.

**Comment by Seanny101** [comment]
Thanks i had a look at that comment and I understand the concern. Sorry to further ask but are some of these special dice, perhaps not all in the Dice so Nice suite already or is this not the case, perhaps interface the dice that are already shown in Dice So Nice. Thanks for considering this idea ,again the Chat Symbols are really good presently.

**Comment by BernhardPosselt** [comment]
Dice so Nice afaik only covers numerical dice, see https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/tree/master/models

**Comment by Seanny101** [comment]
Cool thanks for looking into it for me.
