### ISSUE TITLE
Massive Darkness dice (feature request)

### ISSUE THREAD

**Issue by parvusdomus** [BernhardPosselt/foundryvtt-special-dice-roller#29]
Hello Bernhard,

seeing you are supporting descent 2e, I was wondering if you would add support for Massive Darkness dice (https://boardgamegeek.com/boardgame/197070/massive-darkness).
They are four different 6 sided dices (similar to descent2).

I'm attaching the dice faces in case you wanted to have a look at it.

Thanks in advance
Regards
[DICE.zip](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/files/6177667/DICE.zip)

**Comment by BernhardPosselt** [comment]
Unless you are interested in implementing it on your own, I'm not interested. I own Descent 2nd edition, that's why I went for it.

Dice images need to be compatible with the AGPL.

**Comment by parvusdomus** [comment]
Ok, I understand, no problem, I'll take a look at the dsn custom dices and see what I can do :)
