### ISSUE TITLE
Dice for Dungeon Crawl Classics

### ISSUE THREAD

**Issue by OregonPinkRose** [BernhardPosselt/foundryvtt-special-dice-roller#36]
Would it be possible for a contributor to add the dice for DCC? 
d3, d4, d5, d6, d7, d8, d10, d12, d14, d16, d20, d24, d30, and a d%100. 
I'll tip $5 if it's easy. If it's not easy, we'll have to talk.

**Comment by BernhardPosselt** [comment]
What does Dungeon Crawl Classics do that can't be solved by the built in dice rolling API? https://foundryvtt.com/article/dice/

My understanding was that DCC is very similar to 3rd edition DnD.

PS: just to confirm, you aren't talking about Simple Dice Roller, right?

**Comment by OregonPinkRose** [comment]
After looking into Simple Dice Roller, it looks like that's more what I want to have converted.
You are correct that the API does do what I want it to, and you still have to type in the commands in chat with Special Dice Roller.

**Comment by BernhardPosselt** [comment]
FYI you can also make dice roll macros if you use these dice frequently.
