### ISSUE TITLE
trying to twink ur code to make the roll combo box work

### ISSUE THREAD

**Issue by rafaaiglesias** [BernhardPosselt/foundryvtt-special-dice-roller#40]
![image](https://user-images.githubusercontent.com/21071122/149378509-2c399d66-41e0-47f9-bda7-1be6f413c6c3.png)

like I want to select Blind for GM rolls to work. can I have some leads or it's enterily not supported?

**Comment by BernhardPosselt** [comment]
Hm, was supported actually but looks like it doesn't seem to work on 9.x

**Comment by BernhardPosselt** [comment]
Labelling this as a bug for now. Looks like the chat data that is received in the message hook https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/blob/master/src/index.ts#L72 does not match the full chat data object https://foundryvtt.com/api/data.ChatMessageData.html

Need more feedback from foundry devs for this fix. Either I need to manually parse the select drop down or get it from somewhere else ideally.

**Comment by rafaaiglesias** [comment]
I see. 9.x broke some modules I was running too. at least yours is up and running.
btw thank for your work. Its really something =)

**Comment by rafaaiglesias** [comment]
solved. working at version 9.242

**Comment by BernhardPosselt** [comment]
Thanks for getting back, read it earlier but only logged into GitHub today ;)

Closing this issue then.
