### ISSUE TITLE
Please Please include my rool... Its a simple d6 dicepool which needs reroll function. 

### ISSUE THREAD

**Issue by Jonny134** [BernhardPosselt/foundryvtt-special-dice-roller#55]
Hello, 
Could you please include the dice for my system too? It is almost exactly the same like the black d6 in your current L5R dice system. Except its just the black d6 from that system. I would be very greatful. Please please do this for me. 

The dice is a d6, with the following sides: 
1 Success
2 Success
1 Focus
2 Focus
1 Defense

1 Defense

The roll should have these features: 
Have the ability to coustomize the pool. (How many dice to roll with)
Have the ability to roll. 
Count and summ up all success rolled, all focus rolled, and all defense rolled. 
Send the resoult to the chat.  
Have the ability to keep selected dice from the pool. 
Have the ability to reroll selected dice from the pool. 

I have photoshoped a picture of how i imagine the ned resoult should look:
![garabondice](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/assets/70774182/78879568-3ca8-48ca-a7c3-f7f0184fe353)
(if the symbols could be presented in an increasing order that would be a nice extra, Their order by value would be: 1S, 2S, 1F, 2F, 1D, 1D) 

I am attatching my current module, it incldes the symbols, but you could use any image and I could just replace them. 
[szimfonia-dice-roller_2.zip](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/files/14598152/szimfonia-dice-roller_2.zip)

Thank you in advance.

**Comment by BernhardPosselt** [comment]
Sure, create a pull request to contribute it!

**Comment by Jonny134** [comment]
Im not sure I understand what you mean... Im not a programmer, and I dont know what a pull request is, but i gladly do it if you tell me how... thank you for your quick reply.

**Comment by Jonny134** [comment]
I have tryed, but i am stuck at this step: 
![image](https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/assets/70774182/57a61ea1-762a-4aa3-9b21-6f5f03c1f2c9)
What to do here?

**Comment by BernhardPosselt** [comment]
Check out https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

What you need to do is to select your forked repository in the top right dropdown

**Comment by Jonny134** [comment]
I suppose I should start by installing git and create a forked repository then... right?

**Comment by Jonny134** [comment]
my understanding is that what i am doing is basically create a copy of your module and modify it... but... if I create a copy, and the copy will be stored on my computer then how will you be able to modify it?

**Comment by BernhardPosselt** [comment]
You push your changes to github into your own repository; then there's a button to create a pull request from your uploaded changes.

**Comment by Jonny134** [comment]
Could you just add +1 dice to the original module? peease...  i mean whats the harm? Other people could benefit from my dice to... by replacing the icons... This stuff is waaay tooo advanced for me... If I could do thsese things I would not ask for help, I would just modify your module myself.

**Comment by BernhardPosselt** [comment]
Personally, I'm fine with the current feature set which is what I'm currently using. If you want to see support for your own dice pool invention, please either contribute it or pay a developer to implement it in an acceptable state. My time is currently taken up working on other modules, so I won't spend time to implement this myself.
