### ISSUE TITLE
Issue with Parser alphabet

### ISSUE THREAD

**Issue by gizmo2342** [BernhardPosselt/foundryvtt-special-dice-roller#9]
https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/blob/ca0d05ee023f7419dd039d93e72ff09d9438ee02/src/parser.ts#L43-L65

While doing further testing of the HEXRoller, we stumbled upon an issue with the alphabet. HEXRoller uses "-" as one of the dice character, which causes problems with the RegExp you create in line 53, as it is treated as part of a character range. Other than moving it to the end of the alphabet, there is no real way to work around this issue, as escaping it in the HEXRoller's parser would then cause problems with the letters array created in line 54.

My recommendation would be to check the alphabet for a "-" (and other possibly problematic characters) and escape them before creating the RegExp.

**Comment by BernhardPosselt** [comment]
Yep, just tried that right now :)

Maybe replace the - and + with n for negative and p for positive. Can you create a pull request?
